### ISSUE TITLE
khard move-ing a contact containing "(?)" fails

### ISSUE THREAD

**Issue by GSI** [scheibler/khard#130]
This is the output, when the last name contains `(?)`

```
Traceback (most recent call last):
  File "/home/gsi/.local/bin/khard", line 11, in <module>
    sys.exit(main())
  File "/home/gsi/.local/lib/python3.6/site-packages/khard/khard.py", line 1715, in main
    args.action, vcard_list, args.target_addressbook)
  File "/home/gsi/.local/lib/python3.6/site-packages/khard/khard.py", line 1126, in copy_or_move_subcommand
    True))
  File "/home/gsi/.local/lib/python3.6/site-packages/khard/khard.py", line 454, in get_contact_list_by_user_selection
    config.reverse(), config.group_by_addressbook(), config.sort_by_name())
  File "/home/gsi/.local/lib/python3.6/site-packages/khard/khard.py", line 493, in get_contacts
    re.IGNORECASE | re.DOTALL)
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 856, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, False)
  File "/usr/lib/python3.6/sre_parse.py", line 415, in _parse_sub
    itemsappend(_parse(source, state, verbose))
  File "/usr/lib/python3.6/sre_parse.py", line 750, in _parse
    len(char) + 1)
sre_constants.error: unknown extension ?) at position 20

```

This is the output, when the last name contains `(?`

```
Traceback (most recent call last):
  File "/home/gsi/.local/bin/khard", line 11, in <module>
    sys.exit(main())
  File "/home/gsi/.local/lib/python3.6/site-packages/khard/khard.py", line 1715, in main
    args.action, vcard_list, args.target_addressbook)
  File "/home/gsi/.local/lib/python3.6/site-packages/khard/khard.py", line 1126, in copy_or_move_subcommand
    True))
  File "/home/gsi/.local/lib/python3.6/site-packages/khard/khard.py", line 454, in get_contact_list_by_user_selection
    config.reverse(), config.group_by_addressbook(), config.sort_by_name())
  File "/home/gsi/.local/lib/python3.6/site-packages/khard/khard.py", line 493, in get_contacts
    re.IGNORECASE | re.DOTALL)
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 856, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, False)
  File "/usr/lib/python3.6/sre_parse.py", line 415, in _parse_sub
    itemsappend(_parse(source, state, verbose))
  File "/usr/lib/python3.6/sre_parse.py", line 638, in _parse
    raise source.error("unexpected end of pattern")
sre_constants.error: unexpected end of pattern at position 21
```

**khard modify** works just fine.

**Comment by scheibler** [comment]
Fixed. Please have a look into commit 37ef31fcc7c931bb260fedf375db98a61e473399 for further details.
