### ISSUE TITLE
Unable to modify existing vcards that contain emoji

### ISSUE THREAD

**Issue by samdmarshall** [scheibler/khard#133]
Attempting to modify a vcard file that contains an emoji results in an underlying error from the yaml parser. Wondering if another input format would be appropriate?

```
Traceback (most recent call last):
  File "/usr/local/bin/khard", line 11, in <module>
    load_entry_point('khard==0.11.4', 'console_scripts', 'khard')()
  File "/usr/local/Cellar/khard/0.11.4/libexec/lib/python3.6/site-packages/khard/khard.py", line 1705, in main
    args.open_editor)
  File "/usr/local/Cellar/khard/0.11.4/libexec/lib/python3.6/site-packages/khard/khard.py", line 972, in modify_subcommand
    modify_existing_contact(selected_vcard)
  File "/usr/local/Cellar/khard/0.11.4/libexec/lib/python3.6/site-packages/khard/khard.py", line 112, in modify_existing_contact
    old_contact, new_contact_template)
  File "/usr/local/Cellar/khard/0.11.4/libexec/lib/python3.6/site-packages/khard/carddav_object.py", line 106, in from_existing_contact_with_new_user_input
    contact.process_user_input(user_input)
  File "/usr/local/Cellar/khard/0.11.4/libexec/lib/python3.6/site-packages/khard/carddav_object.py", line 828, in process_user_input
    contact_data = yaml.load(input, Loader=yaml.BaseLoader)
  File "/usr/local/Cellar/khard/0.11.4/libexec/lib/python3.6/site-packages/yaml/__init__.py", line 70, in load
    loader = Loader(stream)
  File "/usr/local/Cellar/khard/0.11.4/libexec/lib/python3.6/site-packages/yaml/loader.py", line 14, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/Cellar/khard/0.11.4/libexec/lib/python3.6/site-packages/yaml/reader.py", line 74, in __init__
    self.check_printable(stream)
  File "/usr/local/Cellar/khard/0.11.4/libexec/lib/python3.6/site-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x1f375: special characters are not allowed
  in "<unicode string>", position 22
```

**Comment by lucc** [comment]
yaml should be able to represent any unicode char so it is likely a problem of the lib.

**Comment by samdmarshall** [comment]
Is this the code in question? https://github.com/yaml/pyyaml

**Comment by lucc** [comment]
yes

**Comment by samdmarshall** [comment]
To update this: there is a PR up on the pyyaml repo that fixes this for over 3 weeks now and judging the previously opened and accepted PRs on that project; it seems unlikely that this will be acted on anytime soon. Would it be possible to consider an alternative yaml parser for this project, or maybe an alternative format (such as TOML or something) for editing in instead?

**Comment by scheibler** [comment]
Parser switched from pyyaml to ruamel.yaml. For me it's working with your emoji placed into the "note" field.

Please pull the latest code from the develop branch and try out again. But beware, that you either
have to re-install khard or install the ruamel.yaml module manually. Otherwise khard would throw an
import error.

**Comment by samdmarshall** [comment]
Sorry i never commented back about this; the solution you provided works perfectly. Thanks so muchh!
