### ISSUE TITLE
self tests assume config file existence

### ISSUE THREAD

**Issue by 0-wiz-0** [scheibler/khard#176]
I tried running the khard-0.12.2 self tests but they failed:
````
running test
running egg_info
writing khard.egg-info/PKG-INFO
writing dependency_links to khard.egg-info/dependency_links.txt
writing entry points to khard.egg-info/entry_points.txt
writing requirements to khard.egg-info/requires.txt
writing top-level names to khard.egg-info/top_level.txt
reading manifest file 'khard.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'khard.egg-info/SOURCES.txt'
running build_ext
Config file .../home/.config/khard/khard.conf not available
*** Error code 3
````
The self-tests shouldn't need that file.

**Comment by lucc** [comment]
I can reproduce this on v0.12.2 but not on develop. Can you reproduce it on develop?

**Comment by 0-wiz-0** [comment]
That seems correct. The `master` branch still uses my .config/khard data, but the `develop` branch doesn't.
There I see a test failure:
````
FAIL: test_simple_bdays_without_options (test.test_command_line_interface.ListingCommands)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/usr/pkg/lib/python3.6/unittest/mock.py", line 1598, in _inner
    return f(*args, **kw)
  File "/disk/6/archive/foreign/khard/test/test_command_line_interface.py", line 83, in test_simple_bdays_without_options
    self.assertListEqual(text, expect)
AssertionError: Lists differ: ['Nam[26 chars]'text birthday     circa 1800', 'second contact    20.01.18'] != ['Nam[26 chars]'text birthday     circa 1800', 'second contact    01/20/2018']

First differing element 2:
'second contact    20.01.18'
'second contact    01/20/2018'

  ['Name              Birthday',
   'text birthday     circa 1800',
-  'second contact    20.01.18']
?                       ^ --

+  'second contact    01/20/2018']
?                     +++  ^^


````
Looks like it has assumptions about the active locale.

**Comment by lucc** [comment]
The above commit fixes the test failure for me.

**Comment by 0-wiz-0** [comment]
That is not sufficient for me. The reason is that in my environment, LC_CTYPE and LC_TIME are set, and only LANG is overridden in the committed patch.

**Comment by lucc** [comment]
Ok, next try :)

**Comment by 0-wiz-0** [comment]
That fixed it, thanks!

````
Ran 55 tests in 0.379s

OK
````
