### ISSUE TITLE
 'str' object has no attribute 'tzinfo'"

### ISSUE THREAD

**Issue by potuz** [scheibler/khard#188]
I think I have experienced this in the past after some upgrade on vobject, but couldn't find it. Anyway I am running khard 0.12.2 and vobject 0.9.6.1 so that this should not be eventable/vobject#120

And still when creating a new VCARD I get

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/khard", line 11, in <module>
    load_entry_point('khard==0.12.2', 'console_scripts', 'khard')()
  File "/usr/lib64/python3.6/site-packages/khard/khard.py", line 1659, in main
    args.open_editor)
  File "/usr/lib64/python3.6/site-packages/khard/khard.py", line 546, in new_subcommand
    create_new_contact(selected_address_book)
  File "/usr/lib64/python3.6/site-packages/khard/khard.py", line 92, in create_new_contact
    new_contact.write_to_file()
  File "/usr/lib64/python3.6/site-packages/khard/carddav_object.py", line 1545, in write_to_file
    f.write(self.vcard.serialize())
  File "/usr/lib64/python3.6/site-packages/vobject/base.py", line 254, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/usr/lib64/python3.6/site-packages/vobject/behavior.py", line 166, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/usr/lib64/python3.6/site-packages/vobject/base.py", line 1007, in defaultSerialize
    child.serialize(outbuf, lineLength, validate=False)
  File "/usr/lib64/python3.6/site-packages/vobject/base.py", line 254, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/usr/lib64/python3.6/site-packages/vobject/behavior.py", line 160, in serialize
    transformed = obj.transformFromNative()
  File "/usr/lib64/python3.6/site-packages/vobject/base.py", line 226, in transformFromNative
    raise NativeError(msg, lineNumber)
vobject.base.NativeError: "In transformFromNative, unhandled exception on line None <class 'AttributeError'>: 'str' object has no attribute 'tzinfo'"
```

**Comment by potuz** [comment]
I'm sorry for the noise, it seems I was still running a 0.9.6 after all, my local ebuild still insisted in downloading from gentoo's servers instead of github.
