### ISSUE TITLE
TypeError: can only concatenate str (not "list") to str

### ISSUE THREAD

**Issue by chilledfrogs** [scheibler/khard#225]
Really sorry if this issue is somehow already here, but try as I may to find it, I haven't, so posting a new issue...

Essentially, on pretty much any operation with `khard` requiring a list of more than 1 contact of some sort (so almost all operations), `khard` spits out the following traceback (the debug messages don't seem to show anything out of the ordinary, but if you guys need it, I will include them, just ask):
```
Traceback (most recent call last):
  File "/bin/khard", line 11, in <module>
    load_entry_point('khard==0.14.0', 'console_scripts', 'khard')()
  File "/usr/lib/python3.7/site-packages/khard/khard.py", line 1786, in main
    vcard_list = generate_contact_list(config, args)
  File "/usr/lib/python3.7/site-packages/khard/khard.py", line 703, in generate_contact_list
    args.strict_search if "strict_search" in args else False)
  File "/usr/lib/python3.7/site-packages/khard/khard.py", line 468, in get_contact_list_by_user_selection
    config.reverse(), config.group_by_addressbook(), config.sort)
  File "/usr/lib/python3.7/site-packages/khard/khard.py", line 494, in get_contacts
    contacts.extend(address_book.search(query, method=method))
  File "/usr/lib/python3.7/site-packages/khard/address_book.py", line 156, in search
    return list(search_function(query))
  File "/usr/lib/python3.7/site-packages/khard/address_book.py", line 84, in _search_all
    contact_details = contact.print_vcard()
  File "/usr/lib/python3.7/site-packages/khard/carddav_object.py", line 1664, in print_vcard
    if self.organisations:
  File "/usr/lib/python3.7/site-packages/khard/carddav_object.py", line 580, in organisations
    return self._get_multi_property("ORG")
  File "/usr/lib/python3.7/site-packages/khard/carddav_object.py", line 138, in _get_multi_property
    values.append(str(ablabel) + ": " + child.value)
TypeError: can only concatenate str (not "list") to str
```

Going indeed to line 137 of carddav_object.py and changing `child.value` to `str(child.value)` ***seems*** to fix the problem, and I don't notice any display issues, but I'm a bit curious as to why this happened in the first place, for the last couple releases...

Thanks in advance guys

**Comment by d7415** [comment]
This looks like it's probably #221.

**Comment by d7415** [comment]
As a stop-gap, maybe we could ignore labels if the length of the list is >1? I think I could draft that quickly. I'll have a look to see if a better option presents itself first.

**Comment by chilledfrogs** [comment]
Thanks, sorry I didn't see #220, so I will wait :) I imported all my contacts from Google to Disroot some time ago, so seems like that would be the problem... Pretty much never edited the vcards manually, so I would have no clue which ones are affected, will use your `sed` command to figure it out

**Comment by d7415** [comment]
@chilledfrogs If you get a chance, could you see if #226 solves this for you?
