### ISSUE TITLE
'ascii' codec can't decode byte 0xc3 in position 4

### ISSUE THREAD

**Issue by DamienCassou** [scheibler/khard#30]
khard used to work, but it does not anymore. Some dependencies have been updated (at least, vobject now comes from https://github.com/tBaxter/vobject).

```
$ khard 
Traceback (most recent call last):
  File "khard-0.6.3/bin/.khard-wrapped", line 10, in <module>
    load_entry_point('khard==0.6.3', 'console_scripts', 'khard')()
  File "khard-0.6.3/lib/python2.7/site-packages/khard/khard.py", line 299, in main
    selected_address_books, args.sort, args.reverse, search_terms[0], False)
  File "khard-0.6.3/lib/python2.7/site-packages/khard/khard.py", line 221, in get_contact_list_by_user_selection
    if regexp.search(contact.print_vcard()) != None:
  File "khard-0.6.3/lib/python2.7/site-packages/khard/carddav_object.py", line 661, in print_vcard
    or self.get_note() != "":
  File "khard-0.6.3/lib/python2.7/site-packages/khard/carddav_object.py", line 294, in get_note
    return self.vcard.note.value.encode("utf-8")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
```

**Comment by scheibler** [comment]
Good to see, that someone updated the slightly old vobject library. But it seems, that the data
fields are already utf-8 encoded now and so khard crashes. I have to investigate, how khard must be
modified to support both vobject versions.

In the meantime you can fix that error by downgrading the installed vobject version manually:
`pip install vobject==0.6.6`

**Comment by DamienCassou** [comment]
0.6.6 is very old. khard seems to work fine with 0.8.1d from https://github.com/adieu/vobject

**Comment by scheibler** [comment]
Please checkout the master branch and try again. I've tested with vobject version 0.8.5.

**Comment by DamienCassou** [comment]
This seems to work fine. Thank you very much.
