### ISSUE TITLE
wrong number of arguments when using khard add-email

### ISSUE THREAD

**Issue by Grauwolf** [scheibler/khard#34]
`set_name_and_organisation` demands 6 arguments but only 4 (counting `self`) are given 

```
% echo "From: Foo Bar <test@example.com>" | khard add-email
Khard: Add email address to contact
Email address: test@example.com
Contact's name [Foo Bar]: 
Contact Foo Bar does not exist. Do you want to create it (y/n)? y
Available address books: default
Address book [default]: 
First name: Foo
Last name: Bar
Organization: Acme Corporation
Traceback (most recent call last):
  File "/usr/bin/khard", line 9, in <module>
    load_entry_point('khard==0.6.3', 'console_scripts', 'khard')()
  File "/usr/lib/python2.7/site-packages/khard/khard.py", line 378, in main
    last_name.decode("utf-8"), organization.decode("utf-8"))
TypeError: set_name_and_organisation() takes exactly 6 arguments (4 given)
```

**Comment by scheibler** [comment]
Thank you for sharing. Fixed in the latest master branch.
