### ISSUE TITLE
Command "python setup.py egg_info" failed 

### ISSUE THREAD

**Issue by ichz** [scheibler/khard#43]
### when i ran ```sudo pip install -r requirements.txt``` show following:

```
Collecting awscli==1.4.2 (from -r requirements.txt (line 13))
  Downloading awscli-1.4.2.tar.gz (239kB)
    100% |████████████████████████████████| 241kB 516kB/s 
Collecting requests (from -r requirements.txt (line 14))
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB)
    100% |████████████████████████████████| 503kB 428kB/s 
Collecting datadog==0.8.0 (from -r requirements.txt (line 15))
  Downloading datadog-0.8.0.tar.gz
Collecting pymongo==3.1 (from -r requirements.txt (line 16))
  Downloading pymongo-3.1.tar.gz (462kB)
    100% |████████████████████████████████| 462kB 437kB/s 
Collecting MySQL-python==1.2.5 (from -r requirements.txt (line 17))
  Downloading MySQL-python-1.2.5.zip (108kB)
    100% |████████████████████████████████| 110kB 3.7MB/s 
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-UV1nPS/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-UV1nPS/MySQL-python
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

### please help me how to do .thank you!

**Comment by scheibler** [comment]
For the InsecurePlatformWarning message, have a look at
http://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent.

But khard doesn't require the mysql and requests packages at all. So it's possible, that your
installation problems have another reason. If you can't fix it, I strongly recommend to use virtual
environments instead.  Please have a look into the khard readme file for installation instructions.

**Comment by ichz** [comment]
thank you
