### ISSUE TITLE
AttributeError w/ local vdirsyncer repository

### ISSUE THREAD

**Issue by moritzheiber** [scheibler/khard#5]
I've installed khard from git according to the documentation. I'm using the following configuration:
```
[addressbooks]
[[XXX]]
path = ~/path/to/vdirsyncer/contacts/

[general]
editor = /usr/bin/vim
default_country = Germany
default_action = list
```
It's basically the example configuration copied over with just the path adjusted for my environment. The directory contains the synced `.vcf` files, the content is correct.

However, when I try to run something as simple as  `khard list` or `khard -s moritz` I get the following backtrace:
```
moe@enigma:~$ khard -s moritz
Traceback (most recent call last):
  File "/home/moe/.local/bin/khard", line 9, in <module>
    load_entry_point('khard==0.2', 'console_scripts', 'khard')()
  File "build/bdist.linux-x86_64/egg/khard/khard.py", line 125, in main
  File "build/bdist.linux-x86_64/egg/khard/config.py", line 114, in get_vcard_objects
  File "build/bdist.linux-x86_64/egg/khard/carddav_object.py", line 302, in print_vcard
  File "build/bdist.linux-x86_64/egg/khard/carddav_object.py", line 167, in get_full_name
  File "/home/moe/.local/lib/python2.7/site-packages/vobject/base.py", line 446, in __getattr__
    raise exceptions.AttributeError, name
AttributeError: fn
```
Environment is:
```
moe@enigma:~$ python -V
Python 2.7.8
moe@enigma:~$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic
```
Any pointers?

**Comment by scheibler** [comment]
Hello,

at least one of your vcard files has no full name attribute (fn) although this should be a mandatory attribute. I've updated the code to deal with that problem. Please try it out.

**Comment by moritzheiber** [comment]
82e0bfb88f44d54215f0457829d6a1fd7fa67a97 fixes it for me. Thanks!
