### ISSUE TITLE
Error in move-command deletes contact

### ISSUE THREAD

**Issue by GSI** [scheibler/khard#53]
I send a `VCF` from Android via email and put it into one of the khard directories.

When `khard move` runs into the following error, **the file is lost/deleted (!)**

```
# khard.py move -s $CONTACT
Move contact $CONTACT from address book $FROMBOOK

Available address books:
  TOBOOK
Into address book: TOBOOK

TOBOOK
None
Traceback (most recent call last):
  File "/PATH/khard.py", line 831, in <module>
    main()
  File "/PATH/khard.py", line 795, in main
    copy_contact(source_vcard, target_address_book, args.action == "move")
  File "/PATH/khard.py", line 214, in copy_contact
    source_contact.write_to_file()
  File "/PATH/carddav_object.py", line 1181, in write_to_file
    f.write(self.vcard.serialize())
  File "/usr/lib/python2.7/site-packages/vobject/base.py", line 186, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/usr/lib/python2.7/site-packages/vobject/behavior.py", line 157, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/usr/lib/python2.7/site-packages/vobject/base.py", line 945, in defaultSerialize
    child.serialize(outbuf, lineLength, validate=False)
  File "/usr/lib/python2.7/site-packages/vobject/base.py", line 186, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/usr/lib/python2.7/site-packages/vobject/vcard.py", line 199, in serialize
    VCardTextBehavior.serialize(obj, buf, lineLength, validate)
  File "/usr/lib/python2.7/site-packages/vobject/behavior.py", line 157, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/usr/lib/python2.7/site-packages/vobject/base.py", line 958, in defaultSerialize
    s.write(':' + obj.value)
  File "/usr/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 1: ordinal not in range(128)

```

**Comment by GSI** [comment]
Same error happens with `khard modify`, but in that case the file is preserved.

**Comment by lucc** [comment]
Can you reproduce this with the new command line interface (current master branch)? And can you provide the file in question (maybe change sensible information but check that it still breaks khard)?

**Comment by scheibler** [comment]
The vcard file should not be deleted anymore if something went wrong during modification. However the
unicode error is only reproducible with the original data.

**Comment by GSI** [comment]
I'm not sure if I still have the correct contact, but I am now unable to reproduce the problem of the undesired deletion.

Here's what happens to the PHOTO part of the file, though.
(I reduced the data, replacing whatever I truncated with `[...]`.)

Maybe the entry was already badly formatted by Android, but I'm still surprised that **khard** converts it into something containing binary data.

```
BEGIN:VCARD
VERSION:2.1
N:foo;bar;;;
FN:foo bar
PHOTO;ENCODING=BASE64;JPEG:/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwM
 [.......................................................................]
 HJOevNdZ8NfileeH5pbm1aSWOOVJfKc5idvMVSuM52lWYflz8teROjTqTfJov68z7qpw8qdDm
 9p7yV7M//Z

END:VCARD
```

```
BEGIN:VCARD^M
VERSION:2.1^M
FN:foo bar^M
N:bar;foo;;;^M
PHOTO;ENCODING=BASE64:ÿØÿà^@^PJFIF^@^A^A^@^@^A^@^A^@^@[...]DèÓ©7É¢þ¼Ïº©ÃÊ<9d>^Noiï%{3ÿÙ^M
END:VCARD^M
```
